FROM nvidia/cuda:12.4.1-cudnn-devel-ubuntu22.04

WORKDIR /rembg

RUN apt-get update && apt-get install -y --no-install-recommends python3-pip python-is-python3 curl && apt-get clean && rm -rf /var/lib/apt/lists/*

COPY . .

RUN python -m pip install ".[gpu,cli]" --break-system-packages
RUN rembg d u2net

ENV PORT=5050
EXPOSE 5050

CMD ["python", "-m", "web.app"]
